---
driver:
  name: vagrant
  synced_folders:
    - ["test/integration/default/data", "/sync_data"]

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-12.04
    run_list:
      - recipe[apt::default]
  - name: ubuntu-14.04
    run_list:
      - recipe[apt::default]
  - name: ubuntu-15.04
    run_list:
      - recipe[apt::default]
  - name: centos-6.7
  - name: centos-7.1
  - name: windows-server-2012r2-standard
    attributes:
      omnibus:
        ruby_version: 2.1.6-x64
      delivery_build:
        chefdk_version: 0.12.0
        delivery-cli:
          artifact: https://s3.amazonaws.com/delivery-packages/cli/delivery-cli-0.0.1%2B20160322081708-1-x64.msi
          checksum: 9232f7f1e48fd048a4bb9b8dbe6ef8dc5b7919153b7b23c3e5485f613c9fbc41
    driver:
      customize:
        memory: 4096
      box: chef/windows-server-2012r2-standard

suites:
  - name: default
    run_list:
      - recipe[delivery_build::default]
    attributes:
      apt:
        compile_time_update: true
      delivery_build:
        trusted_certs:
          Supermarket_Cert: /sync_data/supermarket.crt
    # the below are dummy data, generated purely for test purposes
    encrypted_data_bag_secret_key_path: "test/integration/default/encrypted_data_bag_secret"
    data_bags_path: "test/integration/default/data_bags"

  - name: cli
    run_list:
      - recipe[delivery_build::cli]
    attributes:
      delivery_build:
        delivery-cli:
          options: "--nogpgcheck"
